import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import type { ContentWorkflowOverview } from "@shared/content-workflow";
import { AlertTriangle, BookOpenCheck, CheckCircle2, ClipboardCheck, FilePlus2, Loader2, RefreshCw, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

const emptyOrganisationId = "00000000-0000-4000-8000-000000000000";
const reviewLabel: Record<string, string> = { DRAFT_CREATED: "Draft created", RIGHTS_CLEARED: "Rights cleared", RIGHTS_BLOCKED: "Rights blocked", SAFETY_PASSED: "Safety passed", SAFETY_BLOCKED: "Safety blocked", APPROVED: "Approved", RETIRED: "Retired" };

export default function ContentWorkflow() {
  const organisations = trpc.contentWorkflow.organisations.useQuery();
  const [organisationId, setOrganisationId] = useState<string>();
  useEffect(() => { if (!organisationId && organisations.data?.[0]) setOrganisationId(organisations.data[0].id); }, [organisationId, organisations.data]);
  const overviewInput = useMemo(() => ({ organisationId: organisationId ?? emptyOrganisationId }), [organisationId]);
  const overview = trpc.contentWorkflow.overview.useQuery(overviewInput, { enabled: Boolean(organisationId) });

  return <DashboardLayout><main className="min-h-[calc(100vh-2rem)] bg-[#f8f7f3] text-[#183237]"><div className="mx-auto max-w-7xl space-y-7 px-2 py-4 sm:px-4 lg:px-8 lg:py-8">
    <header className="flex flex-col gap-5 border-b border-[#dfe4de] pb-7 lg:flex-row lg:items-end lg:justify-between"><div className="space-y-3"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#66847d]"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-[#9ccf9b]" />Content stewardship / adult workflow</p><h1 className="text-3xl font-semibold tracking-[-0.04em] sm:text-5xl">Approve the text <em className="font-serif font-normal text-[#688b83]">before it reaches a reader.</em></h1><p className="max-w-2xl text-sm leading-6 text-[#5d7070] sm:text-base">Adults review rights and suitability independently. Teachers select only passages that have cleared both gates.</p></div><Badge className="w-fit gap-2 rounded-full border border-[#b9d9c2] bg-[#edf8ee] px-3 py-1.5 text-[#316b49] hover:bg-[#edf8ee]"><ShieldCheck className="h-3.5 w-3.5" /> Approval is auditable</Badge></header>
    {organisations.isLoading ? <WorkflowLoading /> : organisations.isError ? <WorkflowError onRetry={() => organisations.refetch()} /> : !organisations.data?.length ? <NoOrganisation /> : <>
      <Card className="rounded-2xl border-[#dfe4de] bg-white shadow-sm"><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><label className="text-sm font-medium" htmlFor="content-organisation">Organisation</label><Select value={organisationId} onValueChange={setOrganisationId}><SelectTrigger id="content-organisation" className="w-full bg-[#fbfcf8] sm:max-w-md"><SelectValue placeholder="Choose an organisation" /></SelectTrigger><SelectContent>{organisations.data.map(org => <SelectItem key={org.id} value={org.id}>{org.name} · {org.role.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select><span className="text-xs text-[#70827d]">Role-derived access</span></CardContent></Card>
      {overview.isLoading ? <WorkflowLoading /> : overview.isError ? <WorkflowError onRetry={() => overview.refetch()} /> : overview.data ? <WorkflowContent data={overview.data} onRefresh={() => overview.refetch()} /> : null}
    </>}
  </div></main></DashboardLayout>;
}

function WorkflowContent({ data, onRefresh }: { data: ContentWorkflowOverview; onRefresh: () => void }) {
  const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [region, setRegion] = useState("IE");
  const draft = trpc.contentWorkflow.createDraft.useMutation({ onSuccess: () => { setTitle(""); setBody(""); onRefresh(); } });
  const rights = trpc.contentWorkflow.setRights.useMutation({ onSuccess: onRefresh });
  const safety = trpc.contentWorkflow.setSafety.useMutation({ onSuccess: onRefresh });
  const approve = trpc.contentWorkflow.approve.useMutation({ onSuccess: onRefresh });
  const retire = trpc.contentWorkflow.retire.useMutation({ onSuccess: onRefresh });
  const busy = draft.isPending || rights.isPending || safety.isPending || approve.isPending || retire.isPending;
  const message = [draft, rights, safety, approve, retire].find(action => action.isError)?.error?.message ?? (approve.isSuccess ? "Passage approval has been appended to the review history." : "Changes are recorded as append-only review events.");
  const canGovern = data.organisation.canGovernContent;
  const eventKey = (id: string, action: string) => `content-${id}-${action}-${Date.now()}`;
  return <section className="space-y-5"><div className="grid gap-5 xl:grid-cols-[1.08fr_0.92fr]"><Card className="rounded-2xl border-[#dfe4de] bg-white shadow-sm"><CardHeader><p className="text-xs font-semibold uppercase tracking-[0.17em] text-[#78918b]">Teacher selection</p><CardTitle className="mt-2 flex items-center gap-2 text-xl"><BookOpenCheck className="h-5 w-5 text-[#4f836f]" /> Approved passages</CardTitle></CardHeader><CardContent className="space-y-3">{data.approvedPassages.length ? data.approvedPassages.map(passage => <article key={passage.id} className="rounded-xl border border-[#dfe4de] bg-[#fbfcf8] p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="font-semibold">{passage.title}</h2><p className="mt-1 text-sm leading-6 text-[#637773]">{passage.body}</p></div><Badge className="border-[#b9d9c2] bg-[#edf8ee] text-[#316b49] hover:bg-[#edf8ee]">Approved</Badge></div><p className="mt-3 text-xs text-[#71847f]">Regions: {passage.regionTags.join(", ")} · v{passage.version}</p></article>) : <EmptyCopy icon={<BookOpenCheck className="h-5 w-5" />} text="No passage is approved for teacher selection yet." />}</CardContent></Card>
        <Card className="rounded-2xl border-[#dfe4de] bg-[#f0f6ee] shadow-sm"><CardHeader><p className="text-xs font-semibold uppercase tracking-[0.17em] text-[#6f8a78]">Review integrity</p><CardTitle className="mt-2 flex items-center gap-2 text-xl"><ClipboardCheck className="h-5 w-5 text-[#4f836f]" /> Approval history</CardTitle></CardHeader><CardContent className="space-y-3">{canGovern && data.reviewHistory.length ? data.reviewHistory.map(event => <div key={event.id} className="flex items-center justify-between gap-3 rounded-xl border border-[#d6e3d3] bg-white/75 p-3"><span className="text-sm font-medium">{reviewLabel[event.action]}</span><time className="text-xs text-[#71847f]">{new Date(event.createdAt).toLocaleString()}</time></div>) : <EmptyCopy icon={<ShieldCheck className="h-5 w-5" />} text={canGovern ? "Review actions will appear here." : "Your role can select approved passages but cannot view review history."} />}</CardContent></Card></div>
    {canGovern ? <div className="grid gap-5 xl:grid-cols-[0.85fr_1.15fr]"><Card className="rounded-2xl border-[#dfe4de] bg-white shadow-sm"><CardHeader><p className="text-xs font-semibold uppercase tracking-[0.17em] text-[#78918b]">Content steward</p><CardTitle className="mt-2 flex items-center gap-2 text-xl"><FilePlus2 className="h-5 w-5 text-[#4f836f]" /> Create a draft</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={event => { event.preventDefault(); if (!title.trim() || !body.trim()) return; draft.mutate({ organisationId: data.organisation.id, title, body, regionTags: [region.trim() || "IE"], idempotencyKey: `draft-${data.organisation.id}-${Date.now()}` }); }}><Input aria-label="Passage title" value={title} onChange={event => setTitle(event.target.value)} placeholder="Passage title" maxLength={160} disabled={busy} /><Textarea aria-label="Passage text" value={body} onChange={event => setBody(event.target.value)} placeholder="Paste or write a passage for adult review" maxLength={20_000} className="min-h-32 resize-y" disabled={busy} /><Input aria-label="Region tag" value={region} onChange={event => setRegion(event.target.value)} placeholder="IE" maxLength={20} disabled={busy} /><Button type="submit" disabled={!title.trim() || !body.trim() || busy} className="w-full gap-2 bg-[#183237] text-white hover:bg-[#24484d]">{draft.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <FilePlus2 className="h-4 w-4" />} Create draft</Button></form></CardContent></Card>
      <Card className="rounded-2xl border-[#dfe4de] bg-white shadow-sm"><CardHeader><p className="text-xs font-semibold uppercase tracking-[0.17em] text-[#78918b]">Content steward</p><CardTitle className="mt-2 flex items-center gap-2 text-xl"><CheckCircle2 className="h-5 w-5 text-[#4f836f]" /> Review queue</CardTitle></CardHeader><CardContent className="space-y-4">{data.reviewQueue.length ? data.reviewQueue.map(passage => <article key={passage.id} className="rounded-xl border border-[#dfe4de] bg-[#fbfcf8] p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><h2 className="font-semibold">{passage.title}</h2><p className="mt-1 line-clamp-2 text-sm leading-6 text-[#637773]">{passage.body}</p><div className="mt-3 flex flex-wrap gap-2"><StatusBadge label="Rights" value={passage.rightsStatus} /><StatusBadge label="Safety" value={passage.safetyStatus} /><StatusBadge label="Publication" value={passage.approvalStatus} /></div></div><div className="flex shrink-0 flex-wrap gap-2 self-start"><Button size="sm" variant="outline" disabled={busy} onClick={() => rights.mutate({ passageId: passage.id, rightsStatus: "CLEARED", idempotencyKey: eventKey(passage.id, "rights") })}>Clear rights</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => safety.mutate({ passageId: passage.id, safetyStatus: "PASSED", idempotencyKey: eventKey(passage.id, "safety") })}>Pass safety</Button>{passage.canApprove ? <Button size="sm" disabled={busy} className="bg-[#183237] text-white hover:bg-[#24484d]" onClick={() => approve.mutate({ passageId: passage.id, idempotencyKey: eventKey(passage.id, "approve") })}>Approve</Button> : null}<Button size="sm" variant="ghost" disabled={busy} onClick={() => retire.mutate({ passageId: passage.id, idempotencyKey: eventKey(passage.id, "retire") })}>Retire</Button></div></div></article>) : <EmptyCopy icon={<ClipboardCheck className="h-5 w-5" />} text="The review queue is clear." />}</CardContent></Card></div> : null}
    <p role="status" className={`text-sm ${[draft, rights, safety, approve, retire].some(action => action.isError) ? "text-[#a44e3b]" : "text-[#61766b]"}`}>{message}</p>
  </section>;
}

function StatusBadge({ label, value }: { label: string; value: string }) { const good = value === "CLEARED" || value === "PASSED" || value === "APPROVED"; const bad = value === "BLOCKED"; return <Badge className={good ? "border-[#b9d9c2] bg-[#edf8ee] text-[#316b49] hover:bg-[#edf8ee]" : bad ? "border-[#e8c9c0] bg-[#fff0eb] text-[#a44e3b] hover:bg-[#fff0eb]" : "border-[#dfe4de] bg-white text-[#71847f] hover:bg-white"}>{label}: {value.replaceAll("_", " ")}</Badge>; }
function EmptyCopy({ icon, text }: { icon: React.ReactNode; text: string }) { return <div className="flex min-h-28 flex-col items-center justify-center gap-3 rounded-xl border border-dashed border-[#dfe4de] bg-[#fbfcf8] px-5 text-center text-sm leading-6 text-[#71847f]"><span className="text-[#6e8a82]">{icon}</span>{text}</div>; }
function WorkflowLoading() { return <div className="space-y-5" aria-label="Loading content workflow" aria-busy="true"><div className="h-14 animate-pulse rounded-2xl bg-muted" /><div className="grid gap-5 xl:grid-cols-2"><div className="h-72 animate-pulse rounded-2xl bg-muted" /><div className="h-72 animate-pulse rounded-2xl bg-muted" /></div></div>; }
function WorkflowError({ onRetry }: { onRetry: () => void }) { return <section className="flex min-h-[55vh] items-center justify-center"><Card className="max-w-lg border-[#e8c9c0] bg-[#fffaf8]"><CardContent className="space-y-5 p-8 text-center"><AlertTriangle className="mx-auto h-6 w-6 text-[#a44e3b]" /><div><h2 className="text-xl font-semibold">Content workflow unavailable</h2><p className="mt-2 text-sm leading-6 text-[#637773]">No passage changes have been made. Please retry when the review service is available.</p></div><Button onClick={onRetry} className="gap-2 bg-[#183237] text-white hover:bg-[#24484d]"><RefreshCw className="h-4 w-4" /> Retry loading</Button></CardContent></Card></section>; }
function NoOrganisation() { return <section className="flex min-h-[55vh] items-center justify-center"><Card className="max-w-lg border-[#dfe4de] bg-white"><CardContent className="space-y-3 p-8 text-center"><ShieldCheck className="mx-auto h-6 w-6 text-[#66847d]" /><h2 className="text-xl font-semibold">No eligible organisation</h2><p className="text-sm leading-6 text-[#637773]">Your current role does not have access to approved-passage selection or content review.</p></CardContent></Card></section>; }
