import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCircle2, Clock3, FileAudio, Loader2, PlayCircle, ShieldCheck, UploadCloud } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

const emptyId = "00000000-0000-4000-8000-000000000000";
const statusTone: Record<string, string> = { READY: "border-[#b9d9c2] bg-[#edf8ee] text-[#316b49]", ACTIVE: "border-[#b9d9c2] bg-[#edf8ee] text-[#316b49]", ANALYSING: "border-[#dfd5aa] bg-[#fff8dc] text-[#927a2a]", QUEUED: "border-[#dfd5aa] bg-[#fff8dc] text-[#927a2a]", RUNNING: "border-[#dfd5aa] bg-[#fff8dc] text-[#927a2a]", RETRYING: "border-[#dfd5aa] bg-[#fff8dc] text-[#927a2a]", BLOCKED: "border-[#e8c9c0] bg-[#fff0eb] text-[#a44e3b]", FAILED: "border-[#e8c9c0] bg-[#fff0eb] text-[#a44e3b]", CREATED: "border-[#dfe4de] bg-white text-[#61766b]", UPLOADED: "border-[#dfe4de] bg-white text-[#61766b]", NOT_STARTED: "border-[#dfe4de] bg-white text-[#61766b]" };

export default function SessionDemo() {
  const organisations = trpc.contentWorkflow.organisations.useQuery();
  const learners = trpc.learnerSafety.learners.useQuery();
  const [organisationId, setOrganisationId] = useState<string>();
  const [learnerId, setLearnerId] = useState<string>();
  const [passageId, setPassageId] = useState<string>();
  const [selectedSessionId, setSelectedSessionId] = useState<string>();
  const [file, setFile] = useState<File>();
  useEffect(() => { if (!organisationId && organisations.data?.[0]) setOrganisationId(organisations.data[0].id); }, [organisationId, organisations.data]);
  const contentInput = useMemo(() => ({ organisationId: organisationId ?? emptyId }), [organisationId]);
  const content = trpc.contentWorkflow.overview.useQuery(contentInput, { enabled: Boolean(organisationId) });
  const summary = trpc.hackathonDemo.summary.useQuery(contentInput, { enabled: Boolean(organisationId) });
  const matchingLearners = learners.data?.filter(item => item.organisationId === organisationId) ?? [];
  const create = trpc.hackathonDemo.createSession.useMutation({ onSuccess: record => { setSelectedSessionId(record.id); summary.refetch(); } });
  const upload = trpc.hackathonDemo.recordMockUpload.useMutation({ onSuccess: record => { setSelectedSessionId(record.id); summary.refetch(); } });
  const run = trpc.hackathonDemo.runMockAnalysis.useMutation({ onSuccess: record => { setSelectedSessionId(record.id); summary.refetch(); } });
  const current = summary.data?.sessions.find(session => session.id === selectedSessionId) ?? summary.data?.sessions[0];
  const error = [create, upload, run].find(action => action.isError)?.error?.message;
  const busy = create.isPending || upload.isPending || run.isPending;
  return <DashboardLayout><main className="min-h-[calc(100vh-2rem)] bg-[#f8f7f3] text-[#183237]"><div className="mx-auto max-w-7xl space-y-7 px-2 py-4 sm:px-4 lg:px-8 lg:py-8">
    <header className="flex flex-col justify-between gap-5 border-b border-[#dfe4de] pb-7 lg:flex-row lg:items-end"><div className="space-y-3"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#66847d]"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-[#9ccf9b]" />Hackathon demo / adult-controlled</p><h1 className="text-3xl font-semibold tracking-[-0.04em] sm:text-5xl">Demonstrate the safety path <em className="font-serif font-normal text-[#688b83]">without collecting audio.</em></h1><p className="max-w-2xl text-sm leading-6 text-[#5d7070] sm:text-base">This page records mock upload metadata only. It proves consent gating, durable job states, and safe analysis traces; it does not capture or transmit a recording.</p></div><Badge className="w-fit gap-2 rounded-full border border-[#dfd5aa] bg-[#fff8dc] px-3 py-1.5 text-[#927a2a] hover:bg-[#fff8dc]"><ShieldCheck className="h-3.5 w-3.5" /> Mock data only</Badge></header>
    {organisations.isLoading || learners.isLoading ? <Loading /> : organisations.isError || learners.isError || content.isError || summary.isError ? <LoadError /> : !organisations.data?.length ? <NoAccess /> : <>
      <Card className="rounded-2xl border-[#dfe4de] bg-white shadow-sm"><CardContent className="grid gap-3 p-4 md:grid-cols-[auto_1fr_auto]"><label className="self-center text-sm font-medium" htmlFor="session-organisation">Organisation</label><Select value={organisationId} onValueChange={setOrganisationId}><SelectTrigger id="session-organisation" className="bg-[#fbfcf8]"><SelectValue /></SelectTrigger><SelectContent>{organisations.data.map(org => <SelectItem key={org.id} value={org.id}>{org.name}</SelectItem>)}</SelectContent></Select><span className="self-center text-xs text-[#71847f]">Role-derived access</span></CardContent></Card>
      <section className="grid gap-5 xl:grid-cols-[0.9fr_1.1fr]"><Card className="rounded-2xl border-[#dfe4de] bg-white shadow-sm"><CardHeader><p className="text-xs font-semibold uppercase tracking-[0.17em] text-[#78918b]">Step 1</p><CardTitle className="mt-2 flex items-center gap-2 text-xl"><ShieldCheck className="h-5 w-5 text-[#4f836f]" /> Consent-gated session</CardTitle></CardHeader><CardContent className="space-y-4"><Select value={learnerId} onValueChange={setLearnerId}><SelectTrigger aria-label="Select learner" className="bg-[#fbfcf8]"><SelectValue placeholder="Choose a learner" /></SelectTrigger><SelectContent>{matchingLearners.map(item => <SelectItem key={item.id} value={item.id}>{item.safeLabel}</SelectItem>)}</SelectContent></Select><Select value={passageId} onValueChange={setPassageId}><SelectTrigger aria-label="Select approved passage" className="bg-[#fbfcf8]"><SelectValue placeholder="Choose an approved passage" /></SelectTrigger><SelectContent>{content.data?.approvedPassages.map(item => <SelectItem key={item.id} value={item.id}>{item.title}</SelectItem>)}</SelectContent></Select>{!content.data?.approvedPassages.length ? <p className="rounded-lg bg-[#fff8dc] p-3 text-xs leading-5 text-[#806d2c]">No approved passage is available. Use <strong>Content workflow</strong> to clear rights, pass safety review, and approve a draft first.</p> : null}<Button className="w-full gap-2 bg-[#183237] text-white hover:bg-[#24484d]" disabled={!learnerId || !passageId || busy} onClick={() => create.mutate({ learnerId: learnerId!, passageId: passageId!, idempotencyKey: `mock-session-${Date.now()}` })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <CheckCircle2 className="h-4 w-4" />} Create consent-gated mock session</Button></CardContent></Card>
        <Card className="rounded-2xl border-[#dfe4de] bg-[#f0f6ee] shadow-sm"><CardHeader><p className="text-xs font-semibold uppercase tracking-[0.17em] text-[#6f8a78]">Safety dashboard</p><CardTitle className="mt-2 flex items-center gap-2 text-xl"><Clock3 className="h-5 w-5 text-[#4f836f]" /> Durable demo state</CardTitle></CardHeader><CardContent className="grid grid-cols-3 gap-3"><Metric label="Consent-ready" value={summary.data?.activeConsentCount ?? 0} /><Metric label="Blocked" value={summary.data?.blockedSessionCount ?? 0} /><Metric label="In progress" value={summary.data?.queuedOrRunningJobCount ?? 0} /></CardContent></Card></section>
      {current ? <section className="grid gap-5 xl:grid-cols-[0.9fr_1.1fr]"><Card className="rounded-2xl border-[#dfe4de] bg-white shadow-sm"><CardHeader><p className="text-xs font-semibold uppercase tracking-[0.17em] text-[#78918b]">Step 2</p><CardTitle className="mt-2 flex items-center gap-2 text-xl"><UploadCloud className="h-5 w-5 text-[#4f836f]" /> Mock upload metadata</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><Status value={current.consentStatus} /><Status value={current.sessionStatus} /><Status value={current.uploadStatus} /></div><Input aria-label="Mock audio file" type="file" accept="audio/webm,audio/wav" onChange={event => setFile(event.target.files?.[0])} disabled={busy || current.uploadStatus !== "NOT_STARTED"} /><p className="text-xs leading-5 text-[#71847f]">The chosen filename, media type, and file size are shown in the demo state. Audio bytes are never uploaded or retained.</p><Button className="w-full gap-2 bg-[#183237] text-white hover:bg-[#24484d]" disabled={!file || busy || current.uploadStatus !== "NOT_STARTED"} onClick={() => upload.mutate({ sessionId: current.id, fileName: file!.name, mediaType: file!.type === "audio/wav" ? "audio/wav" : "audio/webm", byteSize: file!.size, idempotencyKey: `mock-upload-${current.id}` })}>{upload.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileAudio className="h-4 w-4" />} Record mock upload</Button><Button variant="outline" className="w-full gap-2 border-[#cadbd1] bg-white" disabled={busy || !current.mayProcessData || current.uploadStatus !== "UPLOADED" || current.job?.status !== "QUEUED"} onClick={() => run.mutate({ sessionId: current.id, idempotencyKey: `mock-analysis-${current.id}` })}>{run.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <PlayCircle className="h-4 w-4" />} Run deterministic mock analysis</Button></CardContent></Card>
        <Card className="rounded-2xl border-[#dfe4de] bg-white shadow-sm"><CardHeader><p className="text-xs font-semibold uppercase tracking-[0.17em] text-[#78918b]">Step 3</p><CardTitle className="mt-2 flex items-center gap-2 text-xl"><CheckCircle2 className="h-5 w-5 text-[#4f836f]" /> Safe trace timeline</CardTitle></CardHeader><CardContent className="space-y-3">{current.job ? <div className="flex items-center justify-between rounded-xl bg-[#f7f8f4] p-3"><span className="text-sm font-medium">Mock analysis · attempt {current.job.attemptCount + 1}</span><Status value={current.job.status} /></div> : <p className="rounded-xl border border-dashed border-[#dfe4de] p-4 text-sm text-[#71847f]">Record a mock upload to queue an auditable analysis trace.</p>}{current.traces.map(trace => <article key={trace.id} className="rounded-xl border border-[#dfe4de] bg-[#fbfcf8] p-3"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#66847d]">{trace.stage.replaceAll("_", " ")}</p><p className="mt-1 text-sm leading-6 text-[#526966]">{trace.safeSummary}</p></article>)}</CardContent></Card></section> : <Card className="rounded-2xl border-dashed border-[#d6e3d3] bg-[#fbfcf8]"><CardContent className="flex min-h-40 flex-col items-center justify-center gap-3 p-6 text-center"><FileAudio className="h-6 w-6 text-[#6e8a82]" /><p className="text-sm leading-6 text-[#71847f]">Create a consent-gated mock session to display its upload state and safe trace.</p></CardContent></Card>}
      {error ? <p role="alert" className="rounded-xl border border-[#e8c9c0] bg-[#fff0eb] p-3 text-sm text-[#a44e3b]"><AlertTriangle className="mr-2 inline h-4 w-4" />{error}</p> : null}
    </>}
  </div></main></DashboardLayout>;
}
function Status({ value }: { value: string }) { return <Badge className={`border ${statusTone[value] ?? statusTone.CREATED} hover:opacity-100`}>{value.replaceAll("_", " ")}</Badge>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border border-[#d6e3d3] bg-white/75 p-4"><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-[#71847f]">{label}</p></div>; }
function Loading() { return <div aria-busy="true" className="space-y-5"><div className="h-36 animate-pulse rounded-2xl bg-muted" /><div className="grid gap-5 xl:grid-cols-2"><div className="h-64 animate-pulse rounded-2xl bg-muted" /><div className="h-64 animate-pulse rounded-2xl bg-muted" /></div></div>; }
function LoadError() { return <Card className="border-[#e8c9c0] bg-[#fffaf8]"><CardContent className="p-7 text-center"><AlertTriangle className="mx-auto h-6 w-6 text-[#a44e3b]" /><h2 className="mt-3 text-xl font-semibold">Hackathon demo unavailable</h2><p className="mt-2 text-sm text-[#637773]">No mock recording or analysis action has been run. Refresh to retry safely.</p></CardContent></Card>; }
function NoAccess() { return <Card className="border-[#dfe4de] bg-white"><CardContent className="p-7 text-center"><ShieldCheck className="mx-auto h-6 w-6 text-[#66847d]" /><h2 className="mt-3 text-xl font-semibold">No eligible organisation</h2><p className="mt-2 text-sm text-[#637773]">An authorised staff membership is required for the adult demo.</p></CardContent></Card>; }
